### ISSUE TITLE
How to get the new flagging ?

### ISSUE THREAD

**Issue by sebmestrallet** [fprotais/preprocess_polycube#1]
Hi François,

For now I was directly using your code [polycube_withHexEx](https://github.com/fprotais/polycube_withHexEx) on a tet mesh and a (per cell facet) flagging. Wanting to avoid potential impossible configurations, I'm looking for putting preprocess_polycube in the middle. But, because this code adds tetrahedra, the flagging is no longer linked to the same cell facets.

So, in order to properly use [polycube_withHexEx](https://github.com/fprotais/polycube_withHexEx), we have to compute a new flagging, suitable for the preprocessed tetra mesh, right ? (new inner facets to -1, splitted tetra inducing labels on different cells, etc)

**Comment by fprotais** [comment]
Sebastien, 
If you are using polycube_withHexEx, I would say that this pre-processing is not needed. My code with HexEx uses a least square approach that will not care about small collapsed elements, and HexEx will usually do a great job at recovering them. 

I would recommended using this code only if you aim for 100% bijective polycube-maps. HexEx was actually build to work with maps no respecting that. If you were to use RobustPolycube, then running this code could improve results a bit, but RobustPolycube still has tools to work with non-100% good map. But it will take longer because it will try to compute a valid map. 

If you actually aim for 100% bijective polycube-maps, we should have a discussion about improving this code: it is currently very sub-optimal. 

Apologies for late response, 
Cheers.

**Comment by sebmestrallet** [comment]
Thank you for the clarification @fprotais 

For now I will be content with direct execution of your hex-meshing codes.

Cheers!
